
server:
  # Servlet（Java用于处理请求的组件）的配置
  servlet:
    # 编码配置
    encoding:
      # 强制使用指定的编码
      force: true
      # 字符集
      charset: UTF-8

# Spring的配置
spring:
  # Profile的配置
  profiles:
    # 激活哪些Profile配置
    active: old
  # Jackson框架的配置
  jackson:
    # 响应的JSON结果中默认包含什么样的属性
    default-property-inclusion: non_null

# Knife4j配置
knife4j:
  # 开启增强模式
  enable: true
