# ################################################################################################# #
# 此文件是【开发环境】的配置文件，必须在主配置中通过spring.profiles.active激活此配置，此文件中的各配置才会生效 #
# ################################################################################################# #

# 服务器的配置
server:
  # 服务占用的端口
  port: 8848

# Spring的配置
spring:
  security:
    user:
      name: username      # 自定义用户名
      password: 123456  # 自定义密码
  # 数据源的配置
  datasource:
    # 连接数据库的URL
    url: jdbc:mysql://localhost:3306/wave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # Druid连接池的配置
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最大激活数量
      max-active: 20
  # Redis配置
#  redis:
#    # 主机
#    host: localhost
#    # 端口
#    port: 6379
#    # 用户名
#    username: ~
#    # 密码
#    password: 123456
#  # servlet配置
  servlet:
    # 上传配置
    multipart:
      # 最大文件尺寸
      max-file-size: 500MB
      # 最大请求尺寸
      max-request-size: 500MB
  # WEB配置
  web:
    # 静态资源配置
    resources:
      # 静态资源文件夹，如果多个，使用英文的逗号分隔，本地路径必须使用 file: 作为前缀
      static-locations: classpath:static, file:${tea-store.upload.root-dir-name}

# 日志配置
logging:
  # 显示级别
  level:
    # 某根包（配置将应用于此包及子孙包）的显示级别
    cn.tedu.tea: trace

# 学茶商城的自定义配置
tea-store:
  # 数据访问的相关配置
  dao:
    # 查询数据时，默认的每页记录数，建议值为10~30之间
    default-query-page-size: 5
  # JWT的配置
  jwt:
    # JWT的有效时长，以分钟为单位
    duration-in-minute: 86400
    # JWT的secretKey
    secret-key: fNesMDkqrJFdsfDSwAbFLJ8SnsHJ438AF72D73aKJSmfdsafdLKKAFKDSJ
  # 文件上传
  upload:
    # 对外访问的主机，必须使用 / 作为最后一个字符
    host: http://localhost:${server.port}/
    # 上传的根级文件夹名称，必须使用 / 作为最后一个字符
    root-dir-name: C:/Users/TEACHER/Desktop/
    # root-dir-name: /Users/chengheng/Desktop/JSD2023
    # 上传的文件夹名称，也会作为访问资源时的URL第1级目录名，必须使用 / 作为最后一个字符
    base-dir-name: resources/
    # 文章图片
    article-image:
      # 允许的文件类型，必须配置文件类型的MIME值，多种类型使用英文的逗号分隔
      types: image/jpeg, image/png, image/gif
      # 最大尺寸，单位：MB
      max-size: 5
    # 商品图片
    goods-image:
      # 允许的文件类型，必须配置文件类型的MIME值，多种类型使用英文的逗号分隔
      types: image/jpeg, image/png, image/gif
      # 最大尺寸，单位：MB
      max-size: 5