# ################################################################################################# #
# 此文件是【开发环境】的配置文件，必须在主配置中通过spring.profiles.active激活此配置，此文件中的各配置才会生效 #
# ################################################################################################# #

# 服务器的配置
server:
  # 服务占用的端口
  port: 8848

# Spring的配置
spring:
  security:
    user:
      name: "admin"  # 设置为空字符串
      password: "admin"  # 设置为空字符串
  # 数据源的配置
  datasource:
    # 连接数据库的URL
    url: jdbc:mysql://localhost:3306/wave?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # Druid连接池的配置
    druid:
      # 初始化连接数量
      initial-size: 5
      # 最大激活数量
      max-active: 20
  # Redis配置
  #  redis:
  #    # 主机
  #    host: localhost
  #    # 端口
  #    port: 6379
  #    # 用户名
  #    username: ~
  #    # 密码
  #    password: 123456
  #  # servlet配置
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:static, file:${}
logging:
  level:
    org.lozunki.wavebackend: trace
wavebackend:
  upload:
    host: http://localhost:${server.port}/
    root-dir-name: C:/Users/zunkilo/.m2/product/
    base-dir-name: resources/
    product-image:
      types: image/jpeg, image/png, image/gif
      max-size: 5
    goods-image:
      types: image/jpeg, image/png, image/gif
      max-size: 5
